# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  dev_venv: ydu-202-searchapp-env
  
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
    
  setup-dev-venv:
    desc: setup developer environment
    cmds:
    - conda create -y  -n {{.dev_venv}} python=3.9 pip pdm
    status:
    - conda run -n {{.dev_venv}} pwd

  show-dev-venv-activate:
    desc: _
    cmds:
      - echo conda activate {{.dev_venv}}

  dev_init:
    desc: init developer mode
    cmds:
    - pdm install

  test:
    desc: run prebuild tests
    cmds:
    - pdm run task test-here

  test-here:
    desc: run prebuild tests
    cmds:
    - pytest -s -v tests

  run-server-here:
    desc: run server
    cmds:
    - python searchup/sup_cli.py start-server

  run-server:
    desc: run server from top
    cmds: [{task: run-server-here}]
  