# https://taskfile.dev

version: '3'

vars:
  dev_venv: ydu-202-searchapp-env
  
tasks:
  default:
    cmds:
      - task -l
    silent: true
    
  setup-dev-venv:
    desc: setup developer environment
    cmds:
    - conda create -y  -n {{.dev_venv}} python=3.9 pip 
    status:
    - conda run -n {{.dev_venv}} pwd

  show-dev-venv-activate:
    desc: |-
      print command that activates venv. 
                              use in shell $(task show-dev-venv-activate)
    cmds:
    - echo conda activate {{.dev_venv}}

  dev_init:
    desc: init developer mode
    cmds:
    - pdm install

  test:
    desc: run prebuild tests
    cmds:
    - task: test-here

  test-here:
    desc: run prebuild tests in active venv
    cmds:
    - pytest -s -v tests

  run-server-here:
    desc: run server in active venv
    cmds:
    - python searchup/sup_cli.py start-server

  run-server:
    desc: run server in pdm __pypackages__
    cmds: [{task: run-server-here}]

  resolve-deps:
    desc: install required dependencies
    cmds:
    - pip install -r req.txt
